:Author: shamhiruthik
:Email: {shamhiruthik14@gmail.com}
:Date: 11/09/2022
:Revision: version#
:License: Public Domain

= Project: {Gesture Based TV Remote Control}

- It is a project on GESTURE BASED TV REMOTE CONTROL using Ultrasonic sensor and IR transmitter interfacing with Arduino UNO. For television we are using HEX code but here we are using RGB LED where the all commands will be shown a serial monitor and with different colours on RGB. We can interface with our TV Where swiping over within the specified range in code shows different colours on RGB and different operations if you are using the TV

== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open this file
2. load the sketch file and run it.

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact shamhiruthik https://id.arduino.cc/shamhiruthik

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | 1234-abcd   | 10
| L1 | Red LED        | 2345-asdf   | 5
| A1 | Arduino Zero   | ABX00066    | 1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
